pipeline {
    agent any
    // options {
    //     skipStagesAfterUnstable()
    // }
    stages {
        stage('Build') {
            steps {
                echo 'Build Stage'
                // sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Test Stage'
                // sh 'mvn test'
            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }
        stage('Deliver') { 
            steps {
                echo 'Deliver Stage'
                // sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
